<%@ Page Title="" Language="C#" MasterPageFile="~/PMPrincipal.Master" AutoEventWireup="true" CodeBehind="MostrarEstudiantes.aspx.cs" Inherits="WebProyecto2_3.MostrarEstudiantes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>



<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <h2>Ver Estudiantes</h2>
<asp:GridView ID="GridView1" AutoGenerateDeleteButton="true" CssClass="mGrid" OnRowDeleting="GridView1_RowDeleting"  runat="server"
    AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged"></asp:GridView>
    
</asp:Content>


