//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.PrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int IDAsistencia { get; set; }
        public Nullable<int> IDCurso { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public Nullable<int> IDEstudiante { get; set; }
        public string Fecha { get; set; }
        public string Tipo { get; set; }
    }
}
