//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.PrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public int IDGrupo { get; set; }
        public Nullable<int> IDCurso { get; set; }
        public Nullable<int> IDProfesor { get; set; }
        public Nullable<int> NumeroGrupo { get; set; }
        public string Horario { get; set; }
        public Nullable<int> IDPeriodo { get; set; }
    }
}
