//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.PrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public int IDGrupo { get; set; }
        public Nullable<int> IDCurso { get; set; }
        public Nullable<int> IDProfesor { get; set; }
        public Nullable<int> NumeroGrupo { get; set; }
        public string Horario { get; set; }
        public Nullable<int> IDPeriodo { get; set; }
    }
}
