//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.PrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public int IDPeriodo { get; set; }
        public string Año { get; set; }
        public string NumeroPeriodo { get; set; }
        public string FechaInicio { get; set; }
        public string FechaFinal { get; set; }
        public string Estado { get; set; }
    }
}
