//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.PrograV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public int IDPeriodo { get; set; }
        public string Año { get; set; }
        public string NumeroPeriodo { get; set; }
        public string FechaInicio { get; set; }
        public string FechaFinal { get; set; }
        public string Estado { get; set; }
    }
}
